name: SSPermissions
main: com.ssplugins.ssp.SSPermissions
version: 2.0.0

author: StarShadow

commands:
  sspermissions:
    description: Manage players and groups.
    aliases: [ssp]
    usage: /ssp <args>